# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(765, 472)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.browse_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.browse_pushButton.setGeometry(QtCore.QRect(290, 370, 161, 41))
        self.browse_pushButton.setObjectName("browse_pushButton")
        self.convert_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.convert_pushButton.setGeometry(QtCore.QRect(290, 320, 161, 41))
        self.convert_pushButton.setObjectName("convert_pushButton")
        self.original_image = QtWidgets.QLabel(self.centralwidget)
        self.original_image.setGeometry(QtCore.QRect(0, 0, 371, 291))
        self.original_image.setAutoFillBackground(False)
        self.original_image.setText("")
        self.original_image.setAlignment(QtCore.Qt.AlignCenter)
        self.original_image.setObjectName("original_image")
        self.result_image = QtWidgets.QLabel(self.centralwidget)
        self.result_image.setGeometry(QtCore.QRect(390, 0, 371, 291))
        self.result_image.setAutoFillBackground(False)
        self.result_image.setText("")
        self.result_image.setAlignment(QtCore.Qt.AlignCenter)
        self.result_image.setObjectName("result_image")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 765, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Converter"))
        self.browse_pushButton.setText(_translate("MainWindow", "Browse Image"))
        self.convert_pushButton.setText(_translate("MainWindow", "Convert"))
