name: check formatting
on: pull_request
jobs:
  black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Format Check & Suggest Changes
        run: |
          echo "Suggest Possible Changes"
          black --diff .
          echo "Format Check"
          black --check --verbose .